name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:coverage
      - run: pnpm build
      - uses: codecov/codecov-action@v3
      - if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'chore(release)')
        run: pnpm publish -q --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
